### ISSUE TITLE
Replace 24AA02E64

### ISSUE THREAD

**Issue by Vitaliy86** [hallard/WeMos-Lora#1]
I cannot find 24AA02E64 for buy, can i replace it?

**Comment by hallard** [comment]
@Vitaliy86 
If you don't have the according code in your firmware, you can skip this chip, it's just in case you need specific unique ID on board and don't want to put in in the code.
you can find it on lot of electronic component provider such as 
-  [digikey](http://www.digikey.com/product-detail/en/microchip-technology/24AA02E64-I-SN/24AA02E64-I-SN-ND/3908643)
- [mouser](http://www.mouser.fr/ProductDetail/Microchip-Technology/24AA02E64-I-SN)
- [TME](http://www.tme.eu/gb/details/24aa02e64-i_sn/serial-eeprom-memories-integ-circ/microchip-technology/#)
