### ISSUE TITLE
SSD1306 Header Alignment

### ISSUE THREAD

**Issue by tkerby** [hallard/WeMos-Lora#2]
Hi

In the 1.1 version the pins for the display on the board edge are out of alignment. The png image you have of the board in the repository also reflects this. 

Thanks

Tim

**Comment by hallard** [comment]
@tkerby 
The pin for the display are not aligned to be able to plug display without soldering it for testing or to let the header connector in place when soldering it, it's called "header lock" and used very often by sparkfun and other ;-)
