### ISSUE TITLE
Does 1.1 version work?

### ISSUE THREAD

**Issue by kragupat** [hallard/WeMos-Lora#4]
Hi ,
I recently ordered the board from pcbs.io  but so far haven't been able to get it working.
Tried it with your LMIC fork version both with and with out the diodes.
Has any one been able to successfully run it with 1.1 version boards.
Wemos keeps crashing right after serial.begin.
Also with the sheild attached I cant upload updated skeptch any more from arduino IDE, works ok if I take out the shield.

Thanks

**Comment by hallard** [comment]
Did you solved your problem?
Version 1.2 works fine. I think I've got old V1.1 working version somewhere.
