### ISSUE TITLE
Please create shield for NiceRF Lora1276 with sensitivity up to -139 dBm

### ISSUE THREAD

**Issue by JosefJezek** [hallard/WeMos-Lora#6]
- https://www.aliexpress.com/item/2pcs-4km-range-Lora-TM100mW-SX1276-SPI-interface-Sensitivity-139-dBm-433MHz-LoRa1276-rf-long-distance/2015211844.html
- http://www.nicerf.com/product_146_136.html

**Comment by JosefJezek** [comment]
RFM95W has sensitivity	-123dBm :-/

https://www.digikey.co.nz/product-detail/en/rf-solutions/RFM95W-868S2/RFM95W-868S2-ND/5051755

**Comment by JosefJezek** [comment]
RN2483 has output power only 14 dBm

@hallard FYI

**Comment by hallard** [comment]
@JosefJezek yes it could be cool but I'm pretty short in time for now and the footprint for this device does not exist for my PCB software Eagle CAD. 
If you find an eagle library for it I can take some time to create it.
