### ISSUE TITLE
Multiplexing made easier

### ISSUE THREAD

**Issue by platenspeler** [hallard/WeMos-Lora#7]
Hi,

I have been implementing the dio0,dio1,dio2 pin multiplexing in my single channel gateway using your excellent PCB.

When doing the same in regular LoRa node using your code I just wondered why you do not use the lmic_pin list. If dio[0]==dio[1] one would assume that you are multplexing the pins for a ESP8266 which will make the code really simple.

Maarten

PS. Something like

> static void hal_io_check() {
    uint8_t i;
  // If two DIO pins are equal, we assume pin multiplexing
  if (lmic_pins.dio[0]==lmic_pins.dio[1])
  {
	// Check IRQ flags in radio module
	if ( radio_has_irq() ) 
		radio_irq_handler(0);
  }
  // 
  else {
    for (i = 0; i < NUM_DIO; ++i) {
        if (lmic_pins.dio[i] == LMIC_UNUSED_PIN)
            continue;

        if (dio_states[i] != digitalRead(lmic_pins.dio[i])) {
            dio_states[i] = !dio_states[i];
            if (dio_states[i])
                radio_irq_handler(i);
        }
    }
  }
}

**Comment by hallard** [comment]
@platenspeler 
Not sure to understand, you are multiplexing DIO pins with diode, and all DIO are so going to only one IO correct ?
If so you just have to check only one pin (the others are set to LMIC_UNUSED_PIN) and the LMIC should works right out of the box without any code modification.

Another possibility is to not connect any GPIO pin and check IRQ register of RFM95 module, the fork to support this No DIO connexion is [here](https://github.com/hallard/arduino-lmic) and works fine on all my nodes ;-)
