### ISSUE TITLE
lolin?

### ISSUE THREAD

**Issue by xor256** [hallard/WeMos-Lora#8]
meybe using https://www.banggood.com/Wemos-Lolin-ESP32-OLED-Module-For-Arduino-ESP32-OLED-WiFi-Bluetooth-Dual-ESP-32-ESP-32S-ESP8266-p-1148119.html 
esp + oled 

what You thing about cc1101 
3 band

**Comment by hallard** [comment]
Something like this maybe ? Sorry long time ago
https://github.com/hallard/LoLin32-Lora
