### ISSUE TITLE
Can't find the right SMA connector to fiit this pcb

### ISSUE THREAD

**Issue by certeza** [hallard/WeMos-Lora#9]
The placement of the center pin seems unusual.
Where can I find the right SMA connector?

**Comment by marssystems** [comment]
These SMA connectors work perfectly for me - 

https://www.ebay.co.uk/itm/5pcs-End-Launch-PCB-Mount-Bulkhead-SMA-Female-RF-Coaxial-Connector-Straight-I6V4/282493230059?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2055119.m1438.l2649

**Comment by certeza** [comment]
Thnx!
